/**
 * GET /api/products/[id]/zip
 *
 * Product 의 모든 OutputImage 를 ZIP 으로 묶어 다운로드.
 * 본인 소유 검증.
 */

import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import { fetchAsBuffer } from '@/lib/storage/r2';

export const maxDuration = 60;

export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
    const session = await auth();
    const userId = (session?.user as any)?.id;
    if (!userId) return NextResponse.json({ error: '로그인 필요' }, { status: 401 });

    const { id } = await ctx.params;
    const product = await prisma.product.findFirst({
        where: { id, userId },
        include: {
            outputImages: { orderBy: { createdAt: 'asc' } },
        },
    });
    if (!product) return NextResponse.json({ error: 'Product 없음' }, { status: 404 });
    if (product.outputImages.length === 0) {
        return NextResponse.json({ error: '처리된 이미지 없음' }, { status: 404 });
    }

    const zip = new JSZip();
    // 각 OutputImage 를 fetch + zip 에 추가
    await Promise.all(
        product.outputImages.map(async (img, i) => {
            try {
                const buf = await fetchAsBuffer(img.r2Url);
                const idx = String(i + 1).padStart(2, '0');
                zip.file(`${idx}.png`, buf);
            } catch (e) {
                console.warn('[zip] fetch failed', img.r2Url, e);
            }
        }),
    );

    // 메타 정보 텍스트도 같이
    const meta = [
        `Product: ${product.title || '(no title)'}`,
        `Source: ${product.source} (${product.sourceUrl})`,
        `Created: ${product.createdAt.toISOString()}`,
        `Images: ${product.outputImages.length}`,
        ``,
        `Generated by pdpbot (https://pdpbot.amakers.co.kr)`,
    ].join('\n');
    zip.file('README.txt', meta);

    const zipBuf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

    const filename = `pdpbot-${product.id.slice(0, 8)}.zip`;
    return new NextResponse(zipBuf, {
        status: 200,
        headers: {
            'Content-Type': 'application/zip',
            'Content-Disposition': `attachment; filename="${filename}"`,
            'Content-Length': String(zipBuf.length),
        },
    });
}
