/**
 * GET /api/products/[id]/zip
 *
 * Product 의 모든 결과를 ZIP 으로 묶어 다운로드.
 *
 * ZIP 구조:
 *   ├─ 01-translated/             # Phase 1 — 한국어 합성 결과 (원본 텍스트 → 한국어)
 *   │  ├─ 01.png, 02.png ...
 *   ├─ 02-generated-page/         # Phase 3 — 신규 상세페이지 자동 생성
 *   │  ├─ section-1-hero.png      # 섹션별 개별 이미지 (선택적 업로드)
 *   │  ├─ section-2-feature.png
 *   │  ├─ ...
 *   │  └─ full-page.png           # 1장 PNG 합성본 (쿠팡/네이버 그대로 업로드 가능)
 *   ├─ analysis.json              # AI 상품 분석 (카테고리, 키워드, 마케팅 카피)
 *   ├─ outline.json               # 페이지 outline (헤드라인, 본문, CTA)
 *   └─ README.txt
 *
 * 본인 소유 검증.
 */

import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { auth } from '@/auth';
import { prisma } from '@/lib/prisma';
import { fetchAsBuffer } from '@/lib/storage/r2';

export const maxDuration = 120;

export async function GET(_req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
    const session = await auth();
    const userId = (session?.user as any)?.id;
    if (!userId) return NextResponse.json({ error: '로그인 필요' }, { status: 401 });

    const { id } = await ctx.params;
    const product = await prisma.product.findFirst({
        where: { id, userId },
        include: {
            outputImages: { orderBy: { createdAt: 'asc' } },
        },
    });
    if (!product) return NextResponse.json({ error: 'Product 없음' }, { status: 404 });

    const zip = new JSZip();
    const meta = (product.metadata as any) || {};

    // Phase 1 — inpaint_translate 결과 (한국어 합성)
    const translatedFolder = zip.folder('01-translated');
    const phase1Images = product.outputImages.filter(o => o.mode === 'inpaint_translate');
    await Promise.all(
        phase1Images.map(async (img, i) => {
            try {
                const buf = await fetchAsBuffer(img.r2Url);
                const idx = String(i + 1).padStart(2, '0');
                translatedFolder?.file(`${idx}.png`, buf);
            } catch (e) {
                console.warn('[zip] phase1 fetch failed', img.r2Url, e);
            }
        }),
    );

    // Phase 3 — ai_generate (섹션 이미지 + 합성 1장 PNG)
    const generatedFolder = zip.folder('02-generated-page');
    const phase3Images = product.outputImages.filter(o => o.mode === 'ai_generate');
    await Promise.all(
        phase3Images.map(async (img) => {
            try {
                const m = (img.metadata as any) || {};
                let filename: string;
                if (m.type === 'composed-page' || m.phase === '3.3') {
                    filename = 'full-page.png';
                } else if (m.phase === '3.2' && typeof m.sectionIdx === 'number') {
                    const idx = String(m.sectionIdx + 1).padStart(2, '0');
                    const type = m.sectionType || 'section';
                    filename = `section-${idx}-${type}.png`;
                } else {
                    filename = `${img.id}.png`;
                }
                const buf = await fetchAsBuffer(img.r2Url);
                generatedFolder?.file(filename, buf);
            } catch (e) {
                console.warn('[zip] phase3 fetch failed', img.r2Url, e);
            }
        }),
    );

    // 분석 결과 JSON (사용자가 키워드·카피 그대로 활용 가능)
    if (meta.analysis) {
        zip.file('analysis.json', JSON.stringify(meta.analysis, null, 2));
    }

    // outline JSON
    if (meta.generatedPage) {
        zip.file('outline.json', JSON.stringify(meta.generatedPage, null, 2));
    }

    // README
    const readme = [
        `pdpbot 결과 ZIP`,
        `===============`,
        ``,
        `상품: ${product.title || '(제목 없음)'}`,
        `출처: ${product.source} (${product.sourceUrl})`,
        `생성일: ${product.createdAt.toISOString()}`,
        `이미지 수: ${product.outputImages.length}장`,
        ``,
        `📁 01-translated/`,
        `   원본 이미지의 텍스트를 한국어로 합성한 결과 (${phase1Images.length}장).`,
        `   쿠팡·네이버 등 한국 채널에 그대로 업로드 가능.`,
        ``,
        `📁 02-generated-page/`,
        `   AI 가 자동 생성한 신규 상세페이지 (${phase3Images.length}장).`,
        `   - section-*.png: 섹션별 개별 이미지 (선택적 업로드)`,
        `   - full-page.png: 모든 섹션 합성된 1장 PNG (한 장으로 업로드 권장)`,
        ``,
        `📄 analysis.json`,
        `   AI 상품 분석 — 카테고리, 핵심 특징, 타겟 고객, 마케팅 카피, SEO 키워드.`,
        `   쿠팡·네이버 상품 등록 시 그대로 복붙해 사용 가능.`,
        ``,
        `📄 outline.json`,
        `   상세페이지 outline — 섹션별 헤드라인 / 본문 / CTA.`,
        ``,
        `Generated by pdpbot — https://pdpbot.amakers.co.kr`,
    ].join('\n');
    zip.file('README.txt', readme);

    const zipBuf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

    const filename = `pdpbot-${(product.title || product.id).slice(0, 30).replace(/[^\w가-힯-]/g, '-')}.zip`;
    return new NextResponse(zipBuf, {
        status: 200,
        headers: {
            'Content-Type': 'application/zip',
            'Content-Disposition': `attachment; filename="${filename}"`,
            'Content-Length': String(zipBuf.length),
        },
    });
}
